export const PLOT_POINT_TYPES = [
  "HUMAN_MESSAGE",
  "AI_MESSAGE",
  "ENVIRONMENT_ENTERED",
  "ENVIRONMENT_LEFT",
  "EVALUATION",
  "AUTH_EMAIL_SENT",
  "BIBLE_VERSE_REFERENCE",
  "PALI_CANON_REFERENCE",
  "USER_THEME_SWITCHED",
] as const;
