name: "Workspace"
attach: false
tmux_options: -L 2pm

windows:
  - Vim: vim
  - Terminal:
  - Watch: bun watch:controllers
  - Packages:
      layout: tiled
      panes:
        - Core:
            - cd ./packages/core
        - UI:
            - cd ./packages/ui
  - Apps:
      layout: tiled
      panes:
        - API:
            - cd ./apps/api
        - CLI:
            - cd ./apps/cli
        - Web:
            - cd ./apps/web
        - CE:
            - cd ./apps/character-engine
