#!/usr/bin/env bash

packages=(
  .
  packages/core
  apps/web
  apps/api
  packages/ui
  apps/cli
)

for i in "${packages[@]}"; do
  if test -f "$i/.tmuxinator.yml"; then
    echo "Loading $i/.tmuxinator.yml"
    $(cd "$i" && tmuxinator start)
  fi
done

tmux -L 2pm attach
